### ISSUE TITLE
MediaProjection shows up red after stopping the service

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#10]
After running the app, there's a red MediaProjection icon that doesn't disappear.

![](https://dl3.pushbulletusercontent.com/Pm8QM7B3U5hTB3BCDmpOxYQUb1MdsrI0/Screenshot_20200417-004024.jpg)

Only force quitting the app removes the icon, which breaks the accessibility setting.

**Comment by reconman** [comment]
Also, is there a way for me to test bug fixes without installing a 2nd version of the apk? I can't replace your version with mine because it's not signed with the same certificate.

**Comment by MathewSachin** [comment]
> Also, is there a way for me to test bug fixes without installing a 2nd version of the apk? I can't replace your version with mine because it's not signed with the same certificate.

I think that is intended behaviour. Release versions of an application should be signed with a different key from the Debug builds.

**Comment by reconman** [comment]
And do you have some tutorial for Xamarin? I'm currently struggling to find the connections between the different kind of files.

Every tutorial I've seen starts with a Layout with some buttons, but your Settings Layout is almost empty.

**Comment by MathewSachin** [comment]
Actually, you don't need to know much about Xamarin. I've not used the Xamarin.Forms library here, only Xamarin.Android, which is pretty much a wrapper around the android library. There are a few minor differences, but basically it's like you're writing Android apps in C#.

The difference in the Settings layout is that it uses the Android Preference library, specifically AndroidX Preference library (for compatibility across various versions of Android).
Preference library allows us to create settings UI pretty easily without worrying much about how they are store, how they are displayed. Android handles that for us.

I'd suggest looking about Android in general. I'm doing the same and just translating it to C#.
I prefer C# over JAVA, that's why I picked Xamarin.
