### ISSUE TITLE
Script doesn't run at random times

### ISSUE THREAD

**Issue by weiliang321** [MathewSachin/Fate-Grand-Automata#111]
I was testing out the script while playing the guda guda event in JP on Nox, but sometimes at random times, the script suddenly stops running the commands anymore and I have to manually finish the battle myself. The script technically has the play button ongoing, but the commands just aren't being executed. Any ideas why?

P.S I also realised how hard it is to click the stop button. When I tried to click stop, the script does not actually stop unless I clicked on it multiple times.

**Comment by MathewSachin** [comment]
The script getting stuck might be related to how the Xamarin (C#) Garbage Collection works on Android. I've also experienced the script doing nothing sometimes and I've found that either the GC was running or the app ran out of memory at those times. We're already in the process of porting the app to Kotlin (Android's default language) now (#108) and memory usage seems stable with it.

Regarding the stop button being hard to click, it is probably due to either the script getting stuck, as mentioned above or the script is in a `wait/sleep` in which case suddenly stopping the script is not possible. I've also improved the second case in the Kotlin port in that when the script has to sleep for a long time, it does so in periods of `1s` checking in between whether the user has requested it to stop.

We're still testing the Kotlin port for bugs and it might take some time before it is released.
But, if you can't wait, I can give you a development build for now.

**Comment by MathewSachin** [comment]
@weiliang321 do you still have this problem in the latest version?

**Comment by MathewSachin** [comment]
@weiliang321 I'm closing this issue now. If you still face this issue you can reopen.
