### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by rafflesiazero** [MathewSachin/Fate-Grand-Automata#123]
Hi! To preface this, this is my first time using a script like this for farming and such. 

And so, I'm having a bit of a difficult time in setting this up so that I can run through the story on my alt account quicker. I've referred to the FGO lua stuff, but I don't know how to translate that to the app itself. So I was thinking that maybe I'm too dumb for this sort of thing, haha. 

Anyway, any and all help would be greatly appreciated in terms of getting started. Thank you so much for your assistance!

**Comment by tchofy** [comment]
Really depends on what you want to do. If you want to farm something with just face cards it's as simple as setting the script to battle mode on the homescreen, open fgo and click the play button on the corner of the screen.

Now if you want to automate 3 turn farming, you need to get to know the autoskill function a little better.

-  First thing you need to do from the homescreen of the app is set your Game Server, since each server has small chances that could make the script click somewhere it shouldn't.

- Next you want to configure Refill options. If you want the script to automatically use apples whenever you're out of AP, click the Enable Refill option, set the amount of times you want the script to refill your AP with apples, and in Resource set what kind of apples you want to use All Apples will use bronze, silver and gold apples, starting with bronze ones (at least in previous versions of the app, dunno about latest) and once you're out of them it'll start using silver apples.

- Our next step is to go to the Support option, all the options here are only relevant if you're farming with face cards, but you'll need to go here to extract the default servant/ce images to get started. You can do that by clicking the 3 dots on the top right of your screen and clicking Extract Default Support Images, that will give you all images of ascension arts of Merlin, Skadi and Waver, and  some basic CEs like Chaldea Lunchtime, Monalisa and Kaleidoscope. The app uses those images to compare with what's on the screen to automatically pick the servant/ce you want it to pick for you.

- Finally, we're going into Auto Skill option, that's where most of the stuff happens. First thing to do is click Enable Auto Skill. If you use the "confirm skill use" in fgo, you'll also want to click that option in the app, so it clicks on "Ok" automatically when you use a skill. Next, you need to create a farming script for the app to use, and you can do that by clicking "Manage Autoskill Configurations", then going to the + icon at the bottom right of your screen. In this screen, you'll give the current script a name, so you know what it is for. So let's say you're farming 3 turn QP Doors, you'll want to name it something like "Doors", so you know what the script does just by reading it's name. Next option is Skill Command, and there's two ways to create the script, the visual way (which I recommend for starters) and the FGO Lua way. Let's talk about the visual way first, since it's easier to use, then I'll explain the preferred support settings.

**Visual/Maker Way**
After clicking Skill command, there's the Maker button on the center left of the screen, clicking it gives you an UI that looks like FGO's battle UI, here you can click buttons as if you were playing fgo, you have each servant's 3 skills, master skills, and the attack button. So let's say you're farming doors with Arash (1st), Medusa (2nd) and Drake (3rd), each with a Kaleidoscope, in this screen you just need to do as if you were playing the game, so:

Click servant 1 3rd skill, click Attack, click Servant 1 NP, click Next Battle, Click Servant 2 3rd skill, click Attack, click Servant 2 NP, click Next Battle, click Click Servant 3 3rd skill, click Attack, click Servant 3 NP, and click Done. That'll send you back to the Auto Skill screen with the code c4,#,f5,#,i6.

**FGO Lua Way**
[Refer to this section of the FGO Lua manual](https://29988122.github.io/Fate-Grand-Order_Lua/#/features?id=autoskill).

**Preffered Servants**
If you extracted the default images earlier in this explanation, it'll give you 3 options by default, Merlin, Skadi and Waver, you can get more options by manually creating more servant images for the app using the Support Image Maker on the homescreen. This is for situations where you need a specific support servant, be it Waver for the 50% NP charge, Merlin for the 20% NP charge + Hero Creation for the 50% buster up, or Skadi for the def down and quick buffs. Multiple options can be selected if you don't mind the script picking a random servant between your selection.

**Preffered CEs**
Same as previous, if you did the extraction, you'll have some default options, like Chaldea Lunchtime, Monalisa, etc. This is where you tell the app to look for a support with a specific CE, like let's say you're farming bond points, you'll want a servant with Chaldea Lunchtime, or if you're farming QP, you'll want a servant with Monalisa, or if you're just farming embers you might want a Berserker with Kaleidoscope to help 3 turn it. This can also be combined with the Preffered servants option, so if you want Waver with Chaldea Lunchtime you can have that. Here you can also set it to only pick supports with a Max Limit Broken CE, ignoring non-MLB CEs. Same as before, multiple options can be selected if you don't mind it picking randomly from the ones you selected.

**Other options you might be interested in**
Back on the homescreen, in the Script Mode there's 4 options, Battle, Lottery, Friend Gacha and Support Image Maker.
Battle is the default option, where if you have Auto Skill scripts configured it'll ask you to pick a script once you start the app, toggle service and click the play button.
Lottery is for auto opening lottery boxes so you don't have to sit there clicking for half an hour.
Friend Gacha is for auto rolling friend points until you're either out of friend points or your servant/ce inventory is full. Can be used for rolling quartz too but I don't recommend.
Support Image Maker is a tool the dev made to make it easier to add extra servants and CEs to the app, which can be used by setting the Script Mode to this. To use it, when you are either on the support selection screen, or the friends screen, when you click the play button it'll automatically take a screenshot of every servant and CE visible on the screen, and then it'll ask you to name every image it snapped, and those will be added to the list of Support/CEs automatically. So let's say you want to add Raikou to the list, all you need is a support with a Raikou, and use this function to take a snap of her art while on the support selection screen, or in the friends screen, while she's visible on the screen.

That should be all, everything else you might need is on the main github page.

**Comment by rafflesiazero** [comment]
Hi there! Thank you for taking the time to answer my question. 

I did what you said to do and what I want to use the script for is to farm the story with, however it's not working. I did everything like you said and when I press the play button on the side of the screen, it just sits there and does nothing. It doesn't automatically select my quest for me, doesn't automatically select my preferred servant (Skadi) -- nothing. I don't know what I could be doing wrong here.

**Comment by tchofy** [comment]
Hmm, weird, I think it should throw some error messages when it's not working. What version of Android are you running? Are you using a phone or an emulator? When you press the play button, does it turn into a stop button?

**Comment by rafflesiazero** [comment]
I'm running Android 7 on the latest version of Nox, and yes, when I press the play button, it does turn into a stop button after it prompts me to select an autoskill config.

**Comment by tchofy** [comment]
Seems like you'll need to enable the Use Root for Screenshots option, otherwise the app is essentially blind to what's on your screen.

To do that, in the app's homescreen click More Options at the very bottom of the screen, and tick the Use Root for Screenshots option. Another thing you might have to do is enable Root in Nox if it's not enabled already. If you don't know how to do it, this link might help with that.

https://www.bignox.com/blog/how-to-root-nox-app-player/

**Comment by rafflesiazero** [comment]
Sorry for the delay! Turns out that I needed to root my device for the app to work. I just now need to configure a few more scripts for it so that it doesn't just spit out errors during battle and so that the battle itself is fully automatic. 

Thank you so much for your help!

**Comment by reconman** [comment]
Here's a recorded guide (unedited): https://gofile.io/d/wnW5Ea

**Comment by MathewSachin** [comment]
I'm closing this issue to reduce clutter.
But, I'm still keeping it pinned on top of issues for the superb writeup by @tchofy.
