### ISSUE TITLE
Autoskill doesnt recognize 2nd turn. 

### ISSUE THREAD

**Issue by IAmLoaf21** [MathewSachin/Fate-Grand-Automata#133]
The auto skill works with arash 3rd skill and NP, but afterwards, it just spams cards...

**Device Info (please fill atleast 'Device model'):**
 - Device model: Realme 5 Pro (has notch)
 - Android Version: Android 10
 - RAM: 8 gb

**Comment by tchofy** [comment]
Can you post your skill command? And maybe a screen recording with the debug mode on? That way it'll be easier to see what's going on. To do that, go to main menu, click More options, and tick the Debug Mode and Record Screen options, then just try to use the app like you usually would. After that, it'll create a file named Record.mp4 on your internal memory/Fate-Grand-Automata folder, and upload that file somewhere, like Streammable, Youtube or any file hosting websites.
Also, after getting the recording, go back to the app and disable both debug and record option, since it's no longer needed.

**Comment by IAmLoaf21** [comment]
Oof, figured it out, I should've just use next battle instead of next turn, my mistake. Sorry! Imma close this now
