### ISSUE TITLE
Selecting a specific servant's face card

### ISSUE THREAD

**Issue by kelpie2** [MathewSachin/Fate-Grand-Automata#137]
Before I get started, I'd just like to say that the app looks fantastic, and seems to work well for the most part. It is certainly a lot more user-friendly than FGOlua, which I've used in the past.

I'd like to request an option to prioritise selecting a specific servant's face card during card selection. This would be especially useful for something like double Skadi with Dantes, where to finish off a beefier wave 3 boss you might want to rely on Dantes' boosted quick card crits. Since Dantes hits most targets neutrally, the weak/netural/resist prioritization wouldn't prioritize his card over Skadi's cards in most cases.

I'd imagine this would require uploading an image of the servant's face card like you to for support selection. I'm hope I'm not asking for something that is too difficult to implement.

**Comment by MathewSachin** [comment]
Implementation aside, for these kinds of features, we need to decide the UI we'll use for configuration. It should be optional since everyone won't want this level of customization.
And if we add support for detecting servant face-cards, there are other features some users want like brave chains and for cases like farming bones with face-cards, we'd like to avoid brave chains for fast clears.
We need to come up with a UI which allows setting this up without too much of a hassle.
This is kind of a disadvantage of having a UI over code I'd say. We have to keep it simple enough for most users.
I'm open to suggestions for this. Do post here if you have an idea in mind.

**Comment by metapone** [comment]
If the UI would be too cluttered adding this feature, how about doing something like [ArchiSteamFarm](https://github.com/JustArchiNET/ArchiSteamFarm): make a dedicate UI (on app/web?) to generate config file for users to download and copy into their phones?

**Comment by tchofy** [comment]
Hmm, maybe something like the Support Image Maker, or use the command card sprites from fgo wiki (fandom), although not all servants have them, unfortunately, and the app would need transparent image detection support, which I'm not sure if the library they use got updated to include that already. Then I guess every Auto-Skill script would need a Card Priority setting that overrides the one in the homescreen.

I did a quick mockup in photoshop that addresses brave chain issues, 
![mockup](https://user-images.githubusercontent.com/64620317/85352737-08679680-b4dd-11ea-8f1a-3374aab078c6.jpg)

If so happens that you drew 5 cards for the same servant, the script will just fallback to the default card priority on the homescreen. Don't think it's a good solution, and it involves a lot of coding, but I guess it's a start.

**Comment by MathewSachin** [comment]
@tchofy We now have Card priority per battle:
<kbd>
<img src="https://user-images.githubusercontent.com/10654537/84568483-6c7fb180-ad9d-11ea-838c-b6f4749d1050.jpg" width="200px">
</kbd>

So having card wise priority over that is too much of hassle.

Instead, why not make the app crop out images for all servants and NPs on screen itself. 
So that user doesn't need to specify any images.
A checkbox can be added to per battle card priority for `Prefer Same servant` or something like that and the script will match the image of the first card with other cards to select the same servant if possible.
So, if the NP is the first card, it'll be as good as preferring a brave chain.

Problems I can see with this approach:
- **Cards before NP:** Should these use the same servant as NP? But, with the way the code works right now, this doesn't seem possible.
- **NP Spam/Danger modes:** In these cases script just clicks on all possible NP locations regardless of whether NPs are available. So, it doesn't know if an NP was actually clicked here. In this case first card will be the first face-card or AutoSkill NP after the spammed NPs.

**Comment by tchofy** [comment]
Oh yes, that's a much better solution, didn't know this app could crop and compare images while still running, that makes things much easier.
Can't say much about those two edge cases, seems like it'd only happen with people that use both facecards and NPs to farm, so I guess it'd need some testing, and maybe it can be planned around, like using class advantage first card with two neutral teammates.
