### ISSUE TITLE
Support Selection

### ISSUE THREAD

**Issue by Guowinson** [MathewSachin/Fate-Grand-Automata#141]
The app keeps refreshing the list even though the support is already in the list, this happens randomly regardless whether i enable and disable preferred CEs.

> MAKE SURE YOU TESTED THE LATEST RELEASE.
![Screenshot_2020-06-23-23-26-00-447_com aniplex fategrandorder en](https://user-images.githubusercontent.com/67333729/85430298-264efd00-b5aa-11ea-872f-75422ec2c2b2.jpg)

> See 'SAMSUNG.md' first, if you're a Samsung user.

**Describe the bug**
Include steps to reproduce the error if required

**Screenshots**
If an error occurred, you can find the message by expanding the app's notification.
It is recommended that you atleast add one screenshot of FGO running on your device.

**Device Info (please fill atleast 'Device model'):**
 - Device model: [e.g. Xiaomi Redmi 4]
 - Screen size: [e.g. 1280x720]
 - Android Version: [e.g. Android 7.1]
 - RAM: [e.g. 3GB]

**Comment by MathewSachin** [comment]
I appreciate you opening the issue, but without any concrete information, we can't really help.
I do know that support selection occasionally misses. There are many factors involved like lags, matching threshold, etc. etc.
Since this is very generic, I'm closing the issue.
If you're able to get a recording of the problem with debug mode (both settings are in More options), then, by all means, reopen this issue.
