### ISSUE TITLE
Story skip does not work

### ISSUE THREAD

**Issue by Semtexs** [MathewSachin/Fate-Grand-Automata#148]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

> See 'SAMSUNG.md' first, if you're a Samsung user.

**Describe the bug**
I got everything setup and it does work if I am going to farm one stage but if I set it up to go through the story stages it never presses skip and if I manually press skip it does not tap the screen when it says "Quest cleared Get reward"
**Screenshots**
If an error occurred, you can find the message by expanding the app's notification.
It is recommended that you atleast add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON (recording functionality is available within the app in `More options`).

**Device Info (please fill atleast 'Device model'):**
Bluestacks, rooted

**Comment by Semtexs** [comment]
Actually the more I mess around with this, is it not capable of completing the story in the first place? Maybe that is my issue

**Comment by MathewSachin** [comment]
Story skip doesn't match correctly right now.
We need to use a transparent image to match it because the background is different everytime.
But, the image matching library we use (OpenCV), has limited support for matching transparent images.
Next update of OpenCV should have that option and we'll update the app to detect story skip button correctly then.

Even then, our main focus for this app is not on story, but on farming free quests.

**Comment by Semtexs** [comment]
In terms of farming one stage then yes I have no problems so far, one question though. Is there a better write up on how to properly set up the servant skills?

**Comment by MathewSachin** [comment]
Did you give the Autoskill maker a try? When you edit the command, there is a button named MAKER.

**Comment by IAmLoaf21** [comment]
What about matching to the part before the images are loaded? When the skip button only has a black background?

**Comment by MathewSachin** [comment]
@IAmLoaf21 That won't work reliably. Loading times vary between phones, and we can't detect when image is loaded.

**Comment by IAmLoaf21** [comment]
What about the blip on the textbox?

**Comment by Eckovc** [comment]
So, I have the same "bug".

1.- When I start the quest the script is able to skip the story, but when I finish the battle, and the **second part of the story** starts the scripts just doesn't know what to do, it completely stops.

2.-Same thing happens when the screen saying "You got a saint quartz" after completing a quest shows. The script just stops working.

**Comment by reconman** [comment]
2. is already fixed in an unofficial version. I can provide you with a link for that if you want.

**Comment by Eckovc** [comment]
Please do. And thank you.

**Comment by reconman** [comment]
https://github.com/MathewSachin/Fate-Grand-Automata/suites/910031127/artifacts/10994327

**Comment by Eckovc** [comment]
I really don't know about programming so it might be super stupid, but wouldn't problem #1 could be fix by repeating the code that makes the it skip the first phase?
Sorry if that was just really dumb, I'm just wondering. 
Thanks for the link.

**Comment by reconman** [comment]
The code is there, it's just that the timing is difficult and transparent images can't be detected well right now.

Depending on the background it sometimes works.
