### ISSUE TITLE
Lottery Script for TW server

### ISSUE THREAD

**Issue by the3dsandwich** [MathewSachin/Fate-Grand-Automata#150]
Hi,

I came across this project a couple weeks back and has been using it in Gilfest 2018 (currently running in TW). Super thanks for this app to exist!

Now I want to see if I can help contribute to making the lottery script work for TW server. I'm new to Kotlin or android development but I can try learning it. Also, as I'm on TW serve I can help extract any images if needed.

Thanks again for this great app!

**Comment by MathewSachin** [comment]
That's really great @the3dsandwich that you're willing to contribute.

Getting the Lottery script to work should be quite simple, even if you're new to Kotlin.

1. First, enable the lottery script for TW
https://github.com/MathewSachin/Fate-Grand-Automata/blob/cc63a13b623ee6bc18c97a8d6d09b49cc7dab6ab/app/src/main/java/com/mathewsachin/fategrandautomata/scripts/entrypoints/AutoLottery.kt#L40

2. Then add images corresponding to:
https://github.com/MathewSachin/Fate-Grand-Automata/blob/master/app/src/main/assets/En/lottery.png
https://github.com/MathewSachin/Fate-Grand-Automata/blob/master/app/src/main/assets/En/StopGifts.png

For cropping the images, take the screenshot of the game in 1280x720.
and crop the regions based on:
https://github.com/MathewSachin/Fate-Grand-Automata/blob/cc63a13b623ee6bc18c97a8d6d09b49cc7dab6ab/app/src/main/java/com/mathewsachin/fategrandautomata/scripts/entrypoints/AutoLottery.kt#L15-L16
Image dimensions are half of the script dimension, so take half of all these values when cropping
e.g.
```
finishedLotteryBoxRegion = Left = 287, Top = 430, Width=35, Height=50
```
I'd recommend to crop it smaller than this size but still within those bounds, we don't want the image matching to miss at edges due to fraction rounding issues when scaling on different devices.

---

On a sidenote, does the TW server has the free quest repeat feature yet? NA got that recently with the engine update and JP has had it for some time.
If it is there, maybe we can add support for that too just by putting in an image.

**Comment by the3dsandwich** [comment]
Thanks for the reply!

TW unfortunately hasn't got the fq repeat feature yet. We're still waiting. 

I'm not sure about the part about cropping images. Am I the one taking screenshots or will the script take care of it (and I have to set it up by changing `Fate-Grand-Automata/app/src/main/java/com/mathewsachin/fategrandautomata/scripts/entrypoints/AutoLottery.kt`)?

I should make a PR once I'm done, right? Thanks!

**Comment by reconman** [comment]
@the3dsandwich You have to take and crop the screenshot yourself to be within the bounds mentioned above. The change to AutoLottery.kt is only about not throwing the exception when the server region is TW.

Yes, you should create a PR with the changes.

**Comment by MathewSachin** [comment]
If you're unsure of how to crop the images, just post them here. We can help out.

We need images of two screens:
1. Lottery Box finished screen (before popup for resetting lottery box)
2. Popup that shows for Present Box full

**Comment by the3dsandwich** [comment]
I got the images!

Though my phone takes them at 2880x1440. I tried my best to photoshop the parts but I can't check whether that's the correct one, also I created a PR, so if it's good please check! Thanks!

![Screenshot_20200703-073445](https://user-images.githubusercontent.com/32169552/86474284-12a75180-bd75-11ea-8a5c-cf4f34c8435a.png)
![Screenshot_20200703-072044](https://user-images.githubusercontent.com/32169552/86474296-1a66f600-bd75-11ea-8dc2-cfc8c2e2083a.png)

**Comment by reconman** [comment]
@MathewSachin I just noticed, we don't even have a JP image for StopGifts!

**Comment by MathewSachin** [comment]
I think we can just wait till the next lottery on JP for that

**Comment by reconman** [comment]
Yup, I'm just wondering how nobody in FGOlua noticed that.
