### ISSUE TITLE
Skill Targetting Bug w/ Waver's First Skill

### ISSUE THREAD

**Issue by calamity1010** [MathewSachin/Fate-Grand-Automata#155]
Simply putting it, I'm attempting to do a 3 turn setup right now, and I'm using a support Waver in the setup. When I use the AutoSkill command that I have setup, which is g1f4,#,de5,#,x11achi4 , it applies Waver's skill to himself when it's supposed to go towards servant 1 (which is my Berserker Lancelot).

![Nox_pFi33Z6F9l](https://user-images.githubusercontent.com/68070343/87055631-9a0c1f00-c1d2-11ea-8f38-5cf2a22dae20.jpg)

 - Device model: I'm on Nox Player, but the "mobile phone model" I'm using is: samsung SM-N950N
 - Screen size: 1600x900
 - Android Version: 7.1.2
 - RAM: 4GB

**Comment by tchofy** [comment]
A recording of the issue might be helpful here. In the app's main menu, go to More Options and tick Debug Mode and Record Screen. After that just use the script as normal for one run, where the issue shows up, and once you click the button to pause the script that'll also stop the recording. A file named record.mp4 will show up on your Fate-Grand-Automata folder, on Nox's internal memory, so just upload that file somewhere so that the dev can check what's wrong.
Oh, and don't forget to untick debug and record options in the app, it'll quickly fill your storage on long farming sessions.

**Comment by calamity1010** [comment]
Sure thing! Lemme get right on that :)

**Comment by MathewSachin** [comment]
@tchofy I don't think the `Record Screen` option would work on Nox. Since that only works with MediaProjection but on Nox we use root to take screenshots.

Still, a video would really help, but you'll have to record it in some other way. Oh, and yeah, make sure to keep Debug mode ON for the recording. It would make it easier to understand the problem.

**Comment by calamity1010** [comment]
Was just about to say I don't know how to find the video itself lol, I can record with another program I have so lemme do that real quick and upload it :)

**Comment by calamity1010** [comment]
https://imgur.com/a/TlgY3z3

There ya go, couldn't upload an MP4 so I had to convert it to a GIF via Imgur

**Comment by MathewSachin** [comment]
Got it! You just have to turn the Skill Confirmation option OFF since you have it OFF in FGO also.

**Comment by calamity1010** [comment]
Oh okay, lemme see if that fixes it.

**Comment by calamity1010** [comment]
Ayyy, awesome, it works now! Thanks for all the help, on top of making this program. Wish you the best!
