### ISSUE TITLE
Support Image Maker Script not working as intended

### ISSUE THREAD

**Issue by frendax** [MathewSachin/Fate-Grand-Automata#160]
Hi, I am new to the app, trying to figure it out. So far my experience has been quite positive, however the one thing that stumps me is the support selection. What I am aiming for is 3T farming, to do this easier, I'm aiming to select certain servants, namely Raikou and Lancelot with MLB kaleidoscope. So I have been using the script to make images, but it doesn't work in the end. When i turn on the battle script, the script continues to scroll down the support list, even when there are multiple Raikous and Lancelots with MLB in my friends list. When i went to check on the images, it turns out that the cropped images were in black and white. Might this be the problem inhibiting the script from selecting the servants?

**Comment by reconman** [comment]
Black and white is definitely not an issue, since we only match in black and white anyways.

Does the support selection work at all for those servants?

**Comment by frendax** [comment]
The script just scrolls over the servants. Maybe something wrong on my end instead? I'm also having some trouble with the autoskill. I recorded a6,f5,g6 but when 2nd round comes, no skill activation happens, and no attempts to click the NP zone occur. I have been cicumventing this by toggling the NP spam option, but its not ideal. The biggest problem is definitely the script just scrolling over servants

**Comment by reconman** [comment]
> I recorded a6,f5,g6

Then you clicked on "Next Turn" instead of "Next Battle". Next Battle means next enemy wave, Next Turn means same wave but different turn.

You can manually fix it by turning it into a6,#,f5,#,g6.

I would need to see screenshots of your AutoSkill setup and general Support settings to see if there's something affecting the support selection, and it would be good if you could post details about your device.

**Comment by frendax** [comment]
Alright, its actually working now, the support selection that is. I had to put the one photo of lancelot and raikou i had into their own folders. 

As for the autoskill, thanks for the clarification as well. Its sorted out too.

Everything is working now, but I have one more question; Is there a way to get the script to skip death animations and such by clicking the screen?

**Comment by tchofy** [comment]
At least not for now. The devs have said the only way to be sure one of the allies died is by having the image of all servants in the game dying built into the app, and have it check the screen often for the sprite of servants dying, and even then it wouldn't be 100% reliable, since servants taking damage also looks just like the death animation.

**Comment by reconman** [comment]
Death animation of your own members like Arash or enemies?

For the first - no there isn't, because it's hard to implement well.
For the second - FGO has a Skip Enemy Fadeout option in the Battle Menu
