### ISSUE TITLE
Auto Reward Screen Screenshot Toggle

### ISSUE THREAD

**Issue by homu-gamepress** [MathewSachin/Fate-Grand-Automata#188]
It would be handy for logging purposes, such as contributing to Atlas Academy, if FGA can automatically screencap the drop screen when toggled.

**Comment by MathewSachin** [comment]
It's quite tricky to do. Once FGA detects that you're on any of the result screens, it taps rapidly on the screen.
To stop and take screenshots on the reward screen this will have to be rewritten completely.

**Comment by homu-gamepress** [comment]
That's unfortunate, but thanks for checking!

**Comment by reconman** [comment]
I mean, anyone could create a fork of FGA and adjust the result screen behavior, granted you know how to program.

This method right here is responsible for handling the result screen:
https://github.com/MathewSachin/Fate-Grand-Automata/blob/master/app/src/main/java/com/mathewsachin/fategrandautomata/scripts/entrypoints/AutoBattle.kt#L135

After making the necessary changes, you would have to build your own APK and transfer new commits to the fork regularly.

We won't do it in the main version because the amount of people who would want this feature is very low.
