### ISSUE TITLE
Add close battle feature for event farming with item boost

### ISSUE THREAD

**Issue by Mitsuki39** [MathewSachin/Fate-Grand-Automata#193]
When you press the repeat button the game does not automatically pick another boost item. Is it possible to add 'close' button feature?

And for the item boost, it's not pressing the 'use' button, but the 'begin without item boost'.

Thanks

**Comment by tchofy** [comment]
Not sure about the Close button, since the game boots you out of the quest selection screen to show you the voice lines of whoever you supported, so the game would have to scan the whole screen for the sprites to know where to click.

As for the second issue, did you set it up in More Options > Boost Item? It's probably set to skip, and you want to set it to use item 1/2/3.

**Comment by Mitsuki39** [comment]
I can press it manually and maybe the other user too. I think it save more time than stop and play the app. But If you can't do it, it's not a problem.

And for the booster, I have set it to 3 for race 1&2 and 1 for race 3 and all of them not pressing the use.

My Device is Redmi 6 with MIUI 10 (Android 8)

**Comment by tchofy** [comment]
Oh, I'm not one of the developers, just a user with some knowledge of how this app works, so I'm not sure it's impossible, just that it doesn't seem likely since the chibi teams could be anywhere on the screen, and simple image recognition may not be enough to match them with cropped sprites, and even then it might be necessary to pan the screen around and there's also the game's UI that could be blocking the view of the sprites, so I think if they tried to implement it, it'd be incredibly inaccurate.

From what I've tested, the app is clicking a few pixels under the Use button
![Screenshot_20200720-124416](https://user-images.githubusercontent.com/64620317/87957536-c94e4600-ca86-11ea-9b39-1d104a56b0ab.jpg)

You should be able to bypass that issue by disabling the Confirm Use of Boost Item on the same screen of the screenshot above, so the app's missclick won't be a problem.

**Comment by MathewSachin** [comment]
What @tchofy said is correct. It's not possible from what I can see. There is also a possibility of script clicking on the wrong quest even if you manually tap to skip voice-lines.

I think they changed the BoostItem UI, and I think the position of the `Use` button might vary depending on the text, so like @tchofy said it's better to disable `Confirm use of Boost Item` in FGO itself.

**Comment by Mitsuki39** [comment]
Thanks for the explanation. I will stick with the stop and play then.

And I will close this request.

**Comment by reconman** [comment]
For me personally this seems like a situation DW didn't foresee. Since the boost item screen appears on the Party Selection screen, and that screen doesn't appear when you repeat the quest, you can never use boost items in repeated runs.

And too bad clicking `Close` doesn't throw you back to the screen where the last quest is in the top right.

It would take a miracle to be able to support using boost items for repeats:

1. Someone who is located in the official NA regions reports the problem to the FGO US support
2. DW can somehow find a solution where you can select the boost item during repeats, updates the server, and probably also updates the APK in the Play Store
3. We look at the UI changes made in 2. and implement this feature.
