### ISSUE TITLE
Option to stop the script when a CE drops

### ISSUE THREAD

**Issue by AlfredPaguio** [MathewSachin/Fate-Grand-Automata#210]
It would be nice if the app remind us how many ce dropped (rainbow chest) while using the app or after the app (script) usage

Useful when you leave the app running while you're sleeping (I'm planning to run the app while I'm sleeping for gilfest btw ahahahaha)

I usually forgot to check my craft essence during events so it would be helpful

Sorry for grammar mistakes

And thank you for creating this app for F2Ps who can't afford ankulua

P.S. for EXP CEs too (sparkling chest)

Do you have discord for this app?

**Comment by MathewSachin** [comment]
It might be possible to do.
But, I don't see a good enough way to show the reminder. If we show it while the script is running, the image matching from the screen will probably get ruined.
I don't think there's much point in showing after stopping after a whole night's run. You should at least check the drops after waking up 🤣.

A good amount of effort would be required for implementing this and I'm not sure everyone would want just reminders. Some people who go for max optimization might even like the script to stop when a CE drops.
Anyway, can you post images of the drops (both rainbow and sparkling)?

> Do you have discord for this app?

We don't have a Discord server (at least not yet). We have a [thread on GamePress](https://community.gamepress.gg/t/automatic-farming-app-fate-grand-automata/72155) which we use for discussions.

@reconman Do we really need a discord server for the app? I've not joined any other servers myself so don't know of the community involvement there, like, if it adds any value over the thread on GamePress. It if does, then sure I'll create one.

**Comment by AlfredPaguio** [comment]
Is discord emote works? I don't find it anywhere because I don't know the exact name of it 
https://cdn.discordapp.com/emojis/616393750012493824.png?v=1
Unfortunately that's all I can find

Thank you for explaining, I will choose optimization too in that case.

**Comment by MathewSachin** [comment]
I took a look at a few images of CE drops. There's a shadow over the images so we'll have to crop the images with the shadow ourselves. The original sprites might not work as it is.

![ce drop](https://user-images.githubusercontent.com/10654537/88677925-838b2080-d10b-11ea-91ef-21cb7823c6d1.jpeg)
![ce drop](https://user-images.githubusercontent.com/10654537/88678022-a0bfef00-d10b-11ea-8ede-980786f816d7.png)

**Comment by AlfredPaguio** [comment]
![Screenshot_2020-07-21-08-30-16-863_com aniplex fategrandorder en](https://user-images.githubusercontent.com/25319699/88689760-77b05600-d12d-11ea-8742-87c3b39f4260.jpg)
![Screenshot_2020-07-25-13-21-39-588_com aniplex fategrandorder en](https://user-images.githubusercontent.com/25319699/88689785-7e3ecd80-d12d-11ea-8b12-d9c0ee162d1c.jpg)

**Comment by reconman** [comment]
> Do we really need a discord server for the app? I've not joined any other servers myself so don't know of the community involvement there, like, if it adds any value over the thread on GamePress. It if does, then sure I'll create one.

Discord fits more if there's lots of community involvement, like if the people can discuss topics themselves and don't necessarily need moderators or channel owners.

One advantage of Discord is that everyone can be notified of important things, but the only important messages we have are releases, which are both sent via E-Mail to watchers and as a message in the Gamepress thread, which will probably get read by people whenever they look into our thread again. But they might miss it if there are too many new comments in the thread.

For talking about how to improve the app somewhat professionally, the best platform is still Github, even though it's uncommon for non-devs to have an account to be able to participate in the discussions. But also not everyone has a Discord account.

If we really wanted to run a Discord server, then we would have to tell everyone on Gamepress to go there and lock the Gamepress thread, otherwise we won't be able to keep up with reading the messages. It's already hard for me to keep track of everything. Telling Gamepress people to go to Discord would mean that the thread doesn't show up in the active FGO threads anymore, so we will have fewer chances of getting new users.

**Comment by MathewSachin** [comment]
I agree, sticking to GitHub and Gamepress would be the best thing to do.
Info about new updates are shown now when the user opens the app (release builds only), so Gamepress thread getting flooded isn't really much of a problem. Also, I think many people would continue using older versions unless they hit some bug or really want the new features.
