### ISSUE TITLE
Automatically detecting new areas/nodes in story map

### ISSUE THREAD

**Issue by IAmLoaf21** [MathewSachin/Fate-Grand-Automata#211]
Can a feature like that be implemented?  Like, by scanning the "Next" Arrow after completing a story quest, if no node is chosen after a few tries?

**Comment by MathewSachin** [comment]
It might be possible if you can crop out that "Next" arrow transparently.

**Comment by IAmLoaf21** [comment]
![NEXT ARROW](https://user-images.githubusercontent.com/64293940/88663471-3eb4b900-d10e-11ea-9370-3105a41e5797.png)
Something like this?

**Comment by MathewSachin** [comment]
I checked my JP account which I use for testing (still at Orleans). The Next icon keeps jumping and also there are clouds which can obstruct the matching.
I checked this image and sadly it doesn't work. We get scores between 0 and 1 for matching and for normal cases we have a threshold of 0.8. So, anything getting score over 0.8 is considered as matching and otherwise not matching.
For this image, I'm getting a score very close to 0.59 irrespective of whether the next icon is currently on screen or not.

What was the size of the screenshot you took? It is important that the original image of screen be 1280x720.
Did you resize the image when cropping? It should be of the original size otherwise it won't match.

**Comment by IAmLoaf21** [comment]
Oh sorry, I just cropped it off the screen on my PC, I'll retry with a 720p screenshot. Also, just wondering, I can't use a higher resolution?

**Comment by MathewSachin** [comment]
No, you can't. Images should be cropped from 720p screenshot. Images of different sizes won't match.

**Comment by IAmLoaf21** [comment]
![NextArrow](https://user-images.githubusercontent.com/64293940/88673231-f354d780-d11a-11ea-8934-7bfde1361054.png)
What about  this? Tried removing as much extra pixels this  time, apparently i used the wrong eraser the first time and didnt completely remove some

**Comment by MathewSachin** [comment]
Still no luck. Scores range between 0.44 to 0.5 which isn't a large enough range.
Well, getting images cropped transparently is tricky in itself. In addition to that, the next icon keeps jumping continuously on the quest screen and there are also things like clouds floating over the screen.

I'm getting the feeling that this would be too complex to do.
BTW, do you have programming experience? if yes, I can help you run the code on your system so that you can see the score there itself and adjust the image accordingly.

**Comment by MathewSachin** [comment]
I tried cropping myself, took too long.
![next](https://user-images.githubusercontent.com/10654537/88758816-04d3c900-d187-11ea-9cdd-fceb882df06a.png)

This image works much better.
Gets a score of 0.6 for valid cases and 0.3 for invalid cases.

**Comment by MathewSachin** [comment]
I give up. Even the image I took only matches with the stage I cropped it from 😞. Doesn't match in Orleans.

**Comment by IAmLoaf21** [comment]
Ah I see... That's too bad

**Comment by JJoszZ** [comment]
Sorry if I'm wrong, but wouldn't be easier to match using a smaller picture as reference? Instead of using the whole "Next" maybe it can work if you just use the arrow below it.

**Comment by tchofy** [comment]
Even after going through the ripped assets we have online, and doing some digging in the apk file myself, I can't seem to find the texture they use for that. It's probably somewhere in the files the game downloads on the fly, and trying to use AssetStudio in it didn't work. Would probably require more digging, and I don't have the knowledge to do it. I'll try and do some more digging with whatever I have in hand and see if I can find it, but from the looks of things it seems it'd be easier to match the 1 inside the red circle close to the quest icon.

**Comment by MathewSachin** [comment]
> Sorry if I'm wrong, but wouldn't be easier to match using a smaller picture as reference? Instead of using the whole "Next" maybe it can work if you just use the arrow below it.

@JJoszZ  Didn't work when I tried. Maybe try yourself? My photoshop skills are not much good. 😆

@tchofy I also couldn't find the sprite in the assets posted here: https://github.com/MathewSachin/Fate-Grand-Automata/issues/210#issuecomment-665021986
The red 1 is also shown for free quests so we can't really use that, and it may not always be 1 if you have interludes or strengthenings left.

![Orleans-678x381](https://user-images.githubusercontent.com/10654537/88872240-5d629f00-d237-11ea-8f27-49abf4bd3aef.png)

I'm really thinking of not adding this feature. It requires scanning the whole screen too which much less efficient than looking in a particular region.

**Comment by JJoszZ** [comment]
Sadly, I don't have photoshop skills... or a pc 😔

**Comment by tchofy** [comment]
Went as far as downloading [this asset dump from FGO CN](http://mechanicalsaviour.blogspot.com/2017/07/sprites-part1-part2-part3.html) that even has stuff like sprites they use for attacks and other vfx, still couldn't find the damn thing. At this point I'm throwing the towel too, unfortunately.

**Comment by Miepmeister** [comment]
hm, dunno if that's possible but would it be an idea to try and use a gif of the next logo instead of a image to try and match with the corresponding spot on map?

**Comment by MathewSachin** [comment]
> hm, dunno if that's possible but would it be an idea to try and use a gif of the next logo instead of a image to try and match with the corresponding spot on map?

I don't know how that could even work lol.

**Comment by MathewSachin** [comment]
The folks at Atlas Academy gave me the sprite for the next arrow.

![icon_spot_next](https://user-images.githubusercontent.com/10654537/90233422-c5ba9e80-de3b-11ea-94c4-b51cfbd8e38d.png)

I'm working on something else, so will give this image a try later.

**Comment by MathewSachin** [comment]
My final decision is to not support this.
