### ISSUE TITLE
Does the app click in diferentes places of skills/NPs or have random tabs like FGOlua? Because if not I think it should be added as it will reduce the probabilities of getting banned.

### ISSUE THREAD

**Issue by duradara** [MathewSachin/Fate-Grand-Automata#240]
The app clicking the same exact position every time may flag us and we will get banned.  
Sorry if my english is bad.

**Comment by MathewSachin** [comment]
If they really want to ban, they won't bother tracking all the click positions and just check that this app is installed 🤣

**Comment by duradara** [comment]
hmm I guess you are right, but another layer of protections is always a good thing. Although I dont know programing so I dont know if doing this would be too difficult to implement.

**Comment by MathewSachin** [comment]
I mean why spend time on this because I don't think DW will even bother putting effort into such things like tracking clicks and instead focus on the features of the game.
Doing this would essentially mean replacing all click locations with regions and then click randomly anywhere inside the regions. Ehh, I got better things to work on.
Well, if someone else wants to submit a pull-request, go ahead!
