### ISSUE TITLE
Stop script when Servant maxed their bond during farming

### ISSUE THREAD

**Issue by yunamon** [MathewSachin/Fate-Grand-Automata#262]
Would be useful since when auto-farming you don't know when your bond will be maxed, especially those support ones, since we would like to level their bond immediately after maxed to avoid loss of points for the next level.

**Comment by MathewSachin** [comment]
An option for this existed before but never worked when I tried. Then, after the repeat screen came to NA, to make the script respond not wait there for like 10 seconds, I had to remove that option.
It's not even something I can test properly. Getting to Bond 10 takes a lot of time, and being an F2P, I continue using my Bond 10 servants because I don't have better alternatives.
So, right now the same part of code handles Bond CEs and CEs rewarded after completing a quest for the first time. And, if we have an option to stio for Bond 10 CEs, it will also stop for quest reward CEs.

**Comment by tchofy** [comment]
One thing I think could be useful is have the app emit either a notification sound, or an alarm if it stays in the same screen doing nothing but scanning for, say, 2 minutes, so you'll be able to tell something went wrong and it needs your help.

**Comment by MathewSachin** [comment]
> One thing I think could be useful is have the app emit either a notification sound, or an alarm if it stays in the same screen doing nothing but scanning for, say, 2 minutes, so you'll be able to tell something went wrong and it needs your help.

Hey, can you open a new issue for this?

**Comment by tchofy** [comment]
Sure.

**Comment by yunamon** [comment]
> An option for this existed before but never worked when I tried. Then, after the repeat screen came to NA, to make the script respond not wait there for like 10 seconds, I had to remove that option.
> It's not even something I can test properly. Getting to Bond 10 takes a lot of time, and being an F2P, I continue using my Bond 10 servants because I don't have better alternatives.
> So, right now the same part of code handles Bond CEs and CEs rewarded after completing a quest for the first time. And, if we have an option to stop for Bond 10 CEs, it will also stop for quest reward CEs.

Which means that option works for Bond 10 CEs? Anything beyond is not possible right now, right?

**Comment by MathewSachin** [comment]
> Which means that option works for Bond 10 CEs? Anything beyond is not possible right now, right?

I'm not sure I get this.

I meant if I add the option to Stop on Bond 10, it will also stop when you get a CE reward for quest completion for 1st time.

**Comment by yunamon** [comment]
Well, we're to farm endlessly the same quest so I guess the option you mentioned won't stop again after the 1st time? Sorry if I totally didn't catch what you mean. ^^;

**Comment by MathewSachin** [comment]
Yeah, you got it right. But, people will get confused and open issues that the script stopped even if it was not a Bond CE so we'll have to make that clear in settings.
Also, I've come to realize that there are many people who use the app for story or 1-time runs instead of endless runs.
So, that'll have to made clear in the option description.

**Comment by yunamon** [comment]
Well I've been using it to farm the materials with ridiculous drop rates... so. www
