### ISSUE TITLE
Resume/continue current Skill Command when opening AutoSkill Maker

### ISSUE THREAD

**Issue by AlfredPaguio** [MathewSachin/Fate-Grand-Automata#270]
This should allow undoing the last command without redoing the entire skill command.

**Comment by AlfredPaguio** [comment]
#271

**Comment by AlfredPaguio** [comment]
#271

**Comment by AlfredPaguio** [comment]
![IMG_20200819_030614](https://user-images.githubusercontent.com/25319699/90555067-63f68d80-e1c9-11ea-84c8-8d6040e8115d.jpg)
![IMG_20200819_030644](https://user-images.githubusercontent.com/25319699/90555083-6953d800-e1c9-11ea-8a10-48daaf00b508.jpg)

**Comment by MathewSachin** [comment]
Ignoring the problems with doing this, this won't be useful without #271 anyway.
I think you'll mostly want to edit in between rather than the end, so unless #271 is done, this isn't relevant.

Now, the problem with this feature is, AutoSkillMaker is a state-machine that has to ensure that the skill command generated is valid, but, there is a textbox given to users, where they can possibly enter invalid commands. Loading invalid commands into AutoSkill maker would just make it crash.

Also, when AutoSkill maker is running it stores the skill command in chunks to allow Undo. Once, it is done, the skill command is stored as a single string like it is shown to users. Loading it back in chunks is possible, even if possible a lot of work, but since it is a textbox, users can enter whatever garbage there and we'll need a lot of validation for that.

I personally won't be doing this.
