### ISSUE TITLE
rearrange Pause and stop buttons

### ISSUE THREAD

**Issue by Miepmeister** [MathewSachin/Fate-Grand-Automata#277]
I like the idea of the pause button but currently I think it might cause problems when playing a script due to the pause and the stop button being next to each other which causes the stop button to be overlaying into the actual game screen (see image) 
![Screenshot_20200820-130837_FateGO](https://user-images.githubusercontent.com/64200805/9076153-7aded200-e2e6-11ea-9ee1-8f193b1975d9.jpg)
my suggestion would be to either rearrange those buttons to be above each other or to be able to shift them around separately should you decide to keep the pause button

**Comment by MathewSachin** [comment]
Stop button always overlays the game for users with 16:9 screens, like on my old phone.
It doesn't cause any problems when both buttons are side-by-side. I considered this before placing them like that.
But, if the pause button is above stop button, the script can click on pause when trying to scroll in support selection.
Moving them around separately isn't a good idea either because pause button is something that disappears when the script is not running and it is not good to mess with the screen when script is running (sure, you could pause the script and do that, but I'm still against it).
