### ISSUE TITLE
Card advantage check for Brave Chain

### ISSUE THREAD

**Issue by Andybui1012** [MathewSachin/Fate-Grand-Automata#303]
So i have been using brave chain after NP feature with Lancelot and 2 skadi but some time the script specifically choose skadi instead of lancelot after np and i'm thinking it might be an image similarity issue and it might help if the script also check the card advantage of the NP and find face card with same level of advantage (which should be easier i presume) before checking for face similarity to reduce the amount of error in image similarity.
(Sorry for no video, i'm using Nox with root so can't record)

**Comment by MathewSachin** [comment]
Brave chains feature was made for cases where all servants in your team have the same advantage.
Sure, it has problems with image matching, that's why I marked it Experimental, but, for DSS with Lancelot, Brave chains feature isn't even needed.
Just give the highest priority to WQ, WB, WA and Lancelot's card will be preferred over Skadi's

Brave chains feature is specifically targetted towards DSS with Dantes where except for Assassin/Rulers, Skadi and Dantes have the same affinity. So, checking advantage there has no point.

**Comment by reconman** [comment]
Speaking from my experience, I've been running Dantes + double Skadi against assassins with brave chain after NP activated and FGA chooses Dantes cards over Skadi.

@Andybui1012 Are you sure you activated the brave chain feature correctly? Also, I think you can record with Nox using the FGA record function in More Options, at least I can do that on my rooted phone.

**Comment by MathewSachin** [comment]
@reconman recording won't work on Nox, it uses MediaProjection. Other desktop screen recorders can be used.

**Comment by reconman** [comment]
Doesn't Nox already have a built-in recorder?

**Comment by MathewSachin** [comment]
Don't really remember if Nox has an in-built recorder. But, FGA can't record by itself on Nox.

**Comment by Andybui1012** [comment]
@reconman, i turned on the brave chain feature After NP, and Cast Noble Phantasm is None. 
@MathewSachin Nox have a built-in recorder but it doesn't work, it just show black screen for everything

**Comment by MathewSachin** [comment]
The video won't help much really. The brave chains feature is unreliable (that's why experimental) because in NPs there is a glow present over the servant image which can cause matching with the face-cards to fail.
I really can't do anything about that. And, I already told why the brave chains feature is not really needed for DSS with Lancelot and just Card priority would be enough in most cases.
So, closing this issue.
