### ISSUE TITLE
App Translation

### ISSUE THREAD

**Issue by ScathachSkadi** [MathewSachin/Fate-Grand-Automata#336]
I think this app needs a translation so people around the world can use it.
As an English speaking Korean, it is very useful for myself, but I found it hard explaining how the app works to my Korean friends.
FGO related proper nouns (ex: noble phantasm) are not easy English words other language speaking people can easily understand.
So I request a tab that can change the language of the app. I can help with the Korean translation.

**Comment by MathewSachin** [comment]
I'll get the UI part ready for translation in a few days.
It'll be great if JP/CN/TW want to step in too.

The script exit messages will only come later as there is more effort required there.

**Comment by MathewSachin** [comment]
Not everything is translatable yet, but I made at least half of the UI translatable.

This file contains English resources:
https://github.com/MathewSachin/Fate-Grand-Automata/blob/master/app/src/main/res/values/localized.xml

This is the file for Korean:
https://github.com/MathewSachin/Fate-Grand-Automata/blob/master/app/src/main/res/values-ko/localized.xml

It's better if you can get someone with Android programming knowledge to do the translations so that they can run the app and see how it looks in Korean for themselves.

JP/CN/TW guys are also welcome to translate. I've added the corresponding file for these languages too.

**Comment by mcloverkorea** [comment]
> Not everything is translatable yet, but I made at least half of the UI translatable.
> 
> This file contains English resources:
> https://github.com/MathewSachin/Fate-Grand-Automata/blob/master/app/src/main/res/values/localized.xml
> 
> This is the file for Korean:
> https://github.com/MathewSachin/Fate-Grand-Automata/blob/master/app/src/main/res/values-ko/localized.xml
> 
> It's better if you can get someone with Android programming knowledge to do the translations so that they can run the app and see how it looks in Korean for themselves.
> 
> JP/CN/TW guys are also welcome to translate. I've added the corresponding file for these languages too.

What part of the English resources code string do I need to change into Korean?

**Comment by reconman** [comment]
The part between `>` and `<` in each line.

`%d` is a placeholder for numbers, `\n` is a line break, and `\'` is needed to use the `'` character in the app, so don't modify those.

**Comment by ScathachSkadi** [comment]
Thank you. Translation done.

**Comment by ScathachSkadi** [comment]
No newline at end of file what does that mean? It keeps saying it cannot compile as well.

**Comment by MathewSachin** [comment]
@ScathachSkadi I've fixed the build. You can get an APK from the build page. There should be a dropdown named Artifacts.

**Comment by ScathachSkadi** [comment]
When will the rest of the parts of the app be ready for translation?

**Comment by MathewSachin** [comment]
I've added a few more for things you pick from multiple values.
Making the messages shown on script exit/error translatable would be too much work, so don't expect anytime soon.

**Comment by ScathachSkadi** [comment]
Would the script error part be available for translation before the update? The most mistake people made was the support preferred mode but not choosing the preferred servant. And they would screenshot it and ask people.

**Comment by MathewSachin** [comment]
I already told you that part is a considerable amount of effort to do and not to expect soon.
Honestly, I'm a bit tired after almost rewriting the AutoSkill module and AutoSkill Maker to support edits and don't want to start anything big soon after. So, you'll have to wait for now.

But, I don't really understand people.
Why do they expect it to pick a support servant/CE when they didn't tell it what to pick? 🤣 
If it did pick something random, then the would've complained it was not the one they wanted 🤷.

Oh, you don't have it that hard. Even people who know English act weirder than that. They'll open feature-requests here for features already present in the app.
Open bug reports for things that weren't the app's fault. Don't read the bug template or fill it properly. 😞

**Comment by ScathachSkadi** [comment]
Oh why aren't there a sad reaction here. Thank you. I will patiently wait until that day comes. Please let me know. And also, there are a lot of people who, including myself, are rooting for you. I hope you don't get sick after working so hard. 😉 Have a good rest!

**Comment by MathewSachin** [comment]
@ScathachSkadi I think I've made most of it translatable now, you can start now.

**Comment by ScathachSkadi** [comment]
@MathewSachin Woah that was way faster than I expected. Starting now.

**Comment by the3dsandwich** [comment]
Hi I just saw this issue and I can help with TW translation, but I'm not sure what exactly are some are the features for example **rearrange cards**, **auto-decrement**, and the difference between **limit number of runs** and **repetitions** in refill.

I'm sure I'll have some more questions along the way but I'll create a PR once I have some progress

**Comment by MathewSachin** [comment]
### Rearrange cards

If there are 3 cards: A, B, C with priorities: A > B > C. Instead of clicking in order: ABC, the app would rearrange to click as ACB so that the effect of card B (which has higher priority than C) would be amplified.
And, for 2 cards after an NP: X > Y, will result in NP Y X.

### Auto-decrement

Auto-decrement means to subtract used apples from repetition setting.
Suppose you set **Repetitions** to 10 and stopped the script after 4 apples were used. When you stop the script, the repetitions setting will be updated to (10-4)=6.

**Limit number of runs** can be used to stop after a specific number of fights. Like if you're clearing a free quest, you can set it to 3. **Repetitions** are for how many apples to use. The script stops when either one of them is reached.
