### ISSUE TITLE
Wait for natural AP regeneration after AP is depleted 

### ISSUE THREAD

**Issue by Whatwaq** [MathewSachin/Fate-Grand-Automata#376]
Instead of the script stopping immediately after you run out of AP, could it wait until the AP reaches the amount needed to repeat the quest (like for ember/qp farming its 40), so that we can just afk from the phone and not use apples. There are some potential problems I already see with this though, for example: 

-If it goes past refresh time while waiting (for example for NA its 0400GMT), when the script attempts to restart the quest again, it will have to get past the initial logo screen, and then dismiss any windows after that (like login bonus) to get back to the quest.

-If the master is careless and doesn’t stop the script after the event ends, the script may continually attempt to get to the event that is already over and could possibly lead to undesired actions (I can’t confirm this, just a hypothetical situation)

-Quest icons change after the refresh time, like for embers it changes from saber/rider to archer/assassin. The change in icon may lead to the script not being able to recognize the quest it’s supposed to repeat? (assuming you use the same team for all farming situations)

**Comment by reconman** [comment]
There are several problems with implementing this:

1. If you just wait for your AP to recover in the Repeat screen and you get enough AP, the dialog will not change, as far as I know. So you have to click on `Close` to be able to start any quest again.
2. If you click on `Close` because your AP ran out, you would have to do click on a quest, check if the apple dialog is there, then close. After some time click on the quest again and check for the apple screen again. Since most quests use up 40 AP, the app is stuck doing that for at least 3 hours every time.
3. If you do such a mode, the device can't be used for anything else during the day, so you can't use this feature on your personal phone. If you use that feature during the night, it will only get you 2-3 quest runs until you wake up. So it only eliminates the need to start FGA in the morning.
4. If a server update happens, you will get kicked out into the start screen. Now how do you get back to the previous quest? Was it an event quest? A Free Quest in America or Salem? A daily quest? You would have to tell FGA which quest it should start and even then, most quests involve map navigation, which is impossible to implement.
5. Running FGA for hours just for checking if the AP are refilled drastically reduces the lifespan of your device.

For those reasons, I would reject this feature request.

**Comment by MathewSachin** [comment]
And, I'm not going to support things like doing story on its own, logging in by itself and picking the quest again and waiting and using AP again because these things can be potentially misused to create bot accounts which don't require any intervention from users.
DW might not mind auto battle but those things would definitely be red flags.
