### ISSUE TITLE
Support Image Maker Noble Phantasm.

### ISSUE THREAD

**Issue by jack25440** [MathewSachin/Fate-Grand-Automata#377]
Just a thought but for gilfest and with people wanting np 5 jarchers, is it possible to implement something with the support image maker where similar to looking for friends names you also look for the whole servants Noble Phantasm name. I don't know how hard it is but if your using something similar to looking for friends names it should be easy. Or as a roundabout way we could just put all the names of friends who have it in the archer slot as the friends names to select. Hope I made it make sense.

**Comment by MathewSachin** [comment]
Your idea is good. But it's too late now, we won't be able to get this done before Gilfest. Already got a few things pending before the next release.

**Comment by TryBane** [comment]
Would likely work, but as I mentioned in another thread, it'd be a good idea to combine this with checking the CEs to make sure the script doesn't do something you aren't expecting like picking a Jarcher with Lunchtime (not that someone would do that.... probably) The Friend Name feature was also created as opposed to doing the Noble Phantasm name because skill levels aren't the same for all of the servants on the list. So the script may select a Jarcher that has lvl 1s for all skills. It may be worth it to just get the Friend Name option working in conjunction with Preferred.

**Comment by MathewSachin** [comment]
I didn't think well about the problems with this idea before.
At all NP levels the only change in the text will the NP level number (1-5). The location of it varies heavily depending on how long the NPs name is. See #334.
If we match the whole name (since we can't know for sure where the NP level number will be), it'll probably match with any level since there will only be a minor difference in those images (just that one Np level number).
So, I think we're back to square 1 (#334).
