### ISSUE TITLE
FGO became lag or freeze when selecting servant skill when this app is running

### ISSUE THREAD

**Issue by Miracutor** [MathewSachin/Fate-Grand-Automata#39]
I was yet unable to complete even one run with this app. When the app selects the servant skill, the FGO became freeze and only became normal after over 10 seconds.  I had not encountered this problem while using AnkuLua.   

To make sure, I tried a run with AnkuLua. It runs smoothly and successfully completed a run.
After that, I closed AnkuLua and run Automata. The lag or freeze usually happens at wave 2 when selecting skill.

## Device details
Device: Xiaomi Mi A2 Lite
Android: Android 9
RAM: 4GB
Server: JP

**Comment by MathewSachin** [comment]
Does the automata app crash, i.e. the play button disappears?
My phone is a Xiaomi Redmi 4 and the app used to crash around the second battle.
The problem was that Xiaomi's battery saver was killing the app.
You can try some workarounds from this site: https://dontkillmyapp.com/xiaomi
AnkuLua might be doing some of these itself by using the `write system settings` permission. But, these kinds of things are different for every manufacturer and difficult to handle across multiple versions. AnkuLua does this well, we practically can't.

If that's not the issue, then it must be related to the app's performance. I've actually got a few things planned.
- AnkuLua matches images in grayscale, we're right now doing in RGB. This might be a cause for higher CPU usage.
- Also, if the screen isn't 720p (yours is 1080p), new memory is allocated for every screenshot for resizing the image to 720p. I failed to notice this before since most of the phones I tested on were 720p.

**Comment by Miracutor** [comment]
My device is an Android One so I followed this: https://dontkillmyapp.com/google and I had done this before starting your app for the first time because I read the comments from GamePress thread. The app itself doesn't crash.

**Comment by MathewSachin** [comment]
Fine! I'll get some performance improvements done in a few days and let you know.

**Comment by MathewSachin** [comment]
We've done a few performance improvements and want to confirm with a  few more users before releasing a new version.

You can download the APK from this page: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/84478986
It'll be in a zipped folder.

Please, let me know if the app works fine now or not.

**Comment by Miracutor** [comment]
I tested the app. I played the auto skill run and left the phone to go to eat for about 10 minutes before coming back and it still running smoothly. So, it works! Thanks for the fixes!

**Comment by MathewSachin** [comment]
Awesome! Expect the new version to be released within a day.
