### ISSUE TITLE
Script stops when two(+) Servants gets Bond rank up after a battle

### ISSUE THREAD

**Issue by zeromic** [MathewSachin/Fate-Grand-Automata#423]
Had the rare case to get two different servant bond level after one mission.

The Script clicks/confirms the first bond level up but then stops.

**Comment by runelt99** [comment]
Similar thing happend to me. Except that it happend every time a servant got bond 10, 2 different times my script stopped and when i looked at it it was stuck on the CE screen about it. Worst part is my gilfest setup has a 3rd servant coming close to bond 10 so the script will be silenced again...

**Comment by MathewSachin** [comment]
First of all, both of @zeromic and @runelt99's problems are different.
The first case is two servants Bond-level up after a fight.
The second case is 2 servants reaching Bond 10 after two different fights.

I understand that having a Debug mode video for these cases could be difficult, but at least could've provided Screenshots where the app got stuck.
From my observation, both these cases are handled correctly.

I'm pretty sure, two or more servants Bond levelling up at the same time was already handled.
Since the issue template wasn't filled and we don't know your phone model, it might just be Samsung/Huawei or something similar full-screen issue. I can't say anything from the info here and with only that much info, the Bot was right in closing it at first.

My MHXA hit Bond 10 recently and her Bond CE was received correctly.
A fix for Bond 10 was done which @reconman reported to me for the PlayStore version.
I think you really might not be on the latest version as you said in the other issue that PlayStore shows no updates. PlayStore won't show updates if you had downloaded the app before it was on PlayStore. You'll have to uninstall and reinstall.

This issue will just stay stagnant without proper info. If anyone encounters the same, provide screenshots.
