### ISSUE TITLE
Improving brave chains when there are card(s) before NP

### ISSUE THREAD

**Issue by Dreamwalk3r** [MathewSachin/Fate-Grand-Automata#426]
As of right now, brave chain detection works fine only if NP doesn't have any cards before it. With brave chain option enabled to "After NP" script will ignore brave chain if there's a card before NP and there are cards with higher priority, for example:
![photo_2020-09-18_15-51-58](https://user-images.githubusercontent.com/1562310/93599848-69611680-f9c7-11ea-8840-0e3bdc43177a.jpg)
In this case, the script will choose B-NP-B when B cards are higher priority than A, missing potential B-NP-A brave chain (which it would pick if there wouldn't be cards before NP, selecting either NP-B-A or NP-A-B depending on the "Rearrange cards" option).

**Comment by TryBane** [comment]
After exploring the code a bit, I believe this is the case because the app doesn't know what NP is going to be clicked when it initially does the "cards clicked" prior to NP.

There are a few ways to resolve this. One is to read ahead of the cards prior to NP clicked skill command to find what the NP that'll be clicked is, then follow that up with passing this information to the "readCommandCards" function that occurs in the "clickBattle" function. This'll allow the app to figure out the NP that'll be cast, so that it can prioritize the cards for the NP + Brave Chain.

This is probably the one that will want to be implemented, since it is the easiest and more modular one to produce. Another method might be to remove the checking for brave chains from readCommandCards and move it to the "clickCommandCards" option, but this is less efficient.

A reason to avoid doing the first option is because it would require the passing of more data, and said data would not always be relevant in cases where Brave Chains aren't wanted. That being said, I think this could be overlooked as the overhead is negligible.

**Comment by MathewSachin** [comment]
Suppose there is only one face card of the servant who will use NP.
In that case, should that face card come before the NP or after. Considering how card priority works, it would come before.

**Comment by Dreamwalk3r** [comment]
It could depend on "rearrange cards", I suppose? If it's on then after, if it's off then before.

**Comment by TryBane** [comment]
I think the problem OP had was that he wanted Nito Brave Chain, which would normally be NP-B-A chain, but he wanted to do the B before the NP for the damage boost. However, the option to precard before NP apparently doesn't work with Brave Chain. Hence why he wanted an updated/improved version of either of the features, hence what I described above.

**Comment by MathewSachin** [comment]
I got what you described above, but, it's not always that you get a brave chain.
I was asking what should happen in that case. Does the same servants face-card go before or after the NP? (if there's only 1 matching facecard).

**Comment by TryBane** [comment]
I would assume it'd go after the NP? But I assume they still follow the preset card priority, so if you had the OPs selection, except didn't have Nito's Arts card there, it'd be Waver Buster - NP - Nito Buster?

That's what I'd assume though different circumstances call for different combinations. Might be able to make a setting where you can choose, but that'd give the user more options they need to define.
