### ISSUE TITLE
Battle mode doesn't work on Huawei P20 Pro (worked fine beforehand)

### ISSUE THREAD

**Issue by kissameo** [MathewSachin/Fate-Grand-Automata#480]
Before opening an issue:
- [Y ] I tested the latest release
- [Y ] I looked at other issues (even the closed ones)
- [ Y] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [Y ] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
I've used this for about a month and there's never been any issue, however as of about 15-ish hours ago, it doesn't work in battle mode. I've tried turning on and off 'Ignore Notch Calculation' and looking to see if I can turn on full screen mode for my phone but there isn't an option for FGO/FGA so I assume it's already as full screen as it can be.

I've also tried some solutions suggested in a thread for Huawei P30 regarding changing notch settings and display settings but it didn't work either.

I'll try to attach a video with debug mode on.
(thank you so much for developing this by the way, it keeps me sane)

**Screenshots**
I'll attach a video instead

**Video**
https://youtu.be/V_ybOUmm74Q

**Device Info (please fill at-least 'Device model'):**
 - Device model: Huawei P20 Pro
 - Screen size: 2240 x 1080
 - Android Version: 9
 - RAM: 6GB

**Comment by reihunter360** [comment]
video's privated o_o;

Did you update FGA recently?

**Comment by kissameo** [comment]
Oh no I'm so sorry, it should be public now! I usually update FGA when updates come out but I can't really remember the last time I updated it. Certainly not in the last few days at least.

**Comment by Danidv** [comment]
I think I may have the same problem. I don't know if what I had was was the last version but it was a recent one and it was called Fate Grand Automata (or something like that, not FGA, and whichever it was it wasn't installed from the Google Play. I used the app today like any other day but at one point it died, and when I tried to open the app again to restart the scripts, it wouldn't open. Usual troubleshooting ensued, which led me to uninstalling it and reinstalling (now through Google Play). Now I can start the app with no problem, but when I try to start the Battle scripts they simply won't work. No reaction, and since it's not doing anything I'm not sure whether it's a detection issue or something else. One thing to note is that the lottery mode still works, so it's not that it can't perform the actual clicks.

I'm on Nox, but if it matters I'm emulating an Android 7, Samsung Galaxy S8+ with 2 core CPU, 2048MB RAM and 960x540 resolution. I also didn't change anything about the emulator or anything else besides the app itself, so if it's not an internal FGA issue then the only thing that could've happened is an overlap with the leftover files from before I updated since the screenshots 
I took with the Support Image Maker still exist.

**Comment by reconman** [comment]
@Danidv Your problem is probably related to not setting the settings the same way. Have you activated Root screenshots as specified in the emulator guide?

**Comment by reconman** [comment]
@kissameo So it looks like it doesn't register the clicks. Can you double check your energy savings options for FGA? Users had similar issues in the past.

**Comment by kissameo** [comment]
@reconman Sorry, I'm not exactly sure what you're talking about, but if it's about power saving mode in general, I've never turned it on before.. I also double checked all my battery settings to make sure there wasn't anything funky going on

**Comment by MathewSachin** [comment]
See #363 and #354

**Comment by kissameo** [comment]
@MathewSachin I tried everything in those threads and as far as I can see, I think force stopping it worked. I thought I was doing that already but apparently it was different? Either way I feel really bad for bothering you like that, so I'm really sorry about that. If you could, can you explain why doing a force stop fixes the app? From my layman's perspective it just seems to be the same thing as reloading a we page.

**Comment by reihunter360** [comment]
@kissameo it helps because you're literally stopping any scripts (that might be running despite you clearly poking the Stop button) from functioning and sorta refreshes the FGA app.

Sometimes scripts does this, like ghost tapping. I've had it happen a few times. Closing the app fully worked like a charm.
