### ISSUE TITLE
Skill Spam Option

### ISSUE THREAD

**Issue by balthanon** [MathewSachin/Fate-Grand-Automata#510]
Before opening an issue:
- [X] No one has asked for this feature before in other issues (even the closed ones)

I think it would be interesting to be able to set up a "Skill Spam" option similar to NP Spam.  My thought on how this could work is if a skill is used in an autoskill and skill spam is enabled, then the next time that skill is off cooldown it runs the skill with the same settings it previously used.  The main potential issue with this that I see is order changes or deaths, expected (Chen Gong/Arash/etc...) or otherwise, potentially causing some discrepancies with targeted skills when the original targets are used.  Unexpected deaths are probably the most difficult to code around and might require being able to recognize when a Servant dies.

**Comment by MathewSachin** [comment]
A similar question popped up on Gamepress around yesterday and what [Mysty wrote in the reply](https://community.gamepress.gg/t/automatic-farming-app-fate-grand-automata/72155/1909?u=mathewsachin) was pretty much what I replied to someone who asked about this earlier.

Detecting servant death is straight-up impossible. You can see my explanations in feature-requests for skipping servant death.

There's no real way to detect skill cooldowns since the app works by image matching.
I guess we can fake that by taking an image of the skill before it is first used and keep matching it every turn to see if it is available.
This would also get around not being able to detect servant death, so that solves that problem unless the servant coming in as replacement has the same skill icon, in that case, that servant's skill will get used on repeat, which should still be fine I guess 🤔.
And for cases like Order Change, when you really want to use that skill again, we can override the previous image.

When a skill target dies, the servant coming in as replacement would become the new target. Not much of a problem again I guess 🤔.
I don't recall how the skill target picker looks when there are only 2 servants left.
If the alignment changes, the skill will be skipped by the click on the top-right corner so that the script can keep working, so I guess that's fine too 🤔.

But, since I mostly use FGA when 3-turning, this would be difficult for me to implement or test.
When I can't 3T due to servant bonus or more than 3 enemies per wave, I resort to playing manually since that is more efficient.
I'm already having a hard time testing out #469 😆.

**Comment by balthanon** [comment]
3 turning is definitely the preferred route when possible.  I think this would primarily be for (like mentioned in Misty's reply) those rare spawn boosted events where you want to face card and then possibly more relevantly, new players who have limited rosters.  I'm playing an account right now with an artificially limited roster and for the most part I've found that I don't care too much about efficiency when I'm running Fate Grand Automata with it, so long as the Servants don't actually die, spamming skills would help with that a bit. :) 

That said, you can also do a poor man's version of this (other than accounting for dead Servants) by setting up skill triggers for different waves and then hoping for the best.  FGA handles skills off cooldown gracefully, so it doesn't hurt anything-- so I wouldn't say this is a super high priority either, though handling character death/cooldowns with the before/after images would be useful functionality I would think.  Hopefully not quite as bad to test as #469 though-- random issues are pretty much the worst. :)

For skills when you have only two servants, the space is just completely empty, incidentally.  https://www.youtube.com/watch?v=rSxG5CTKtfw (this is a good example from a solo run.)

(Do you allow other contributors incidentally?  I haven't done any development with the language you're using, but could be an interesting project at some point if this is put on the back burner.)

**Comment by MathewSachin** [comment]
I did a quick implementation in #511 and it seems to work for the 2-3 runs I did.
Build: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/298678242

Skill spam is always ON in that build and starts when AutoSkill command has finished, just like NP spam.

I did pretty much what I wrote in the previous comment: taking images of skills when they're used in AutoSkill, then keep matching them every turn to see if it is available again.

Regarding the 2 servants remaining in battle, I was talking about this case: https://youtu.be/-ZTZlN4IKoI?t=499
The target locations have changed so skill targetting would pretty much fail. The window would be exited after that so at least it won't stop the script.

<img src="https://user-images.githubusercontent.com/10654537/95645607-7a8cd700-0ade-11eb-8e32-f1c08a0fdf1e.png" width="500">

You're surely welcome to contribute. Kotlin should be a good language to learn too since it's like the successor to Java in Android development and is now the official language of Android.
Just follow the standard GitHub way of sending pull-requests. And also let me know beforehand if you're working on something so we can avoid redundant work.

**Comment by balthanon** [comment]
Nice.  I'll give this a try tomorrow morning probably.  Just finished using up my AP for the evening and I'll probably be passing out early since I was up till like 4 in the morning playing Genshin Impact. :P

I'll take a look at Kotlin.  I was wondering what was going on with Java usage in Android given the lawsuit between Google and Oracle and the recent Supreme Court hearing; hadn't taken time to look it up before now though.

**Comment by MathewSachin** [comment]
Google had won that case. You can still use Java to make Android apps. It's just that Java hasn't evolved as much as other languages like C# have.
IIRC, the verdict was that APIs can't be copyrighted.

In Java, you have to write a lot of boilerplate which Kotlin gets rid of.
Kotlin runs on Java Virtual Machine and also brings many productivity improvements which is why Google chose to make it the main language for Android and not really due to the lawsuit.
