### ISSUE TITLE
Give priority on MLB CE when the MLB option is unchecked

### ISSUE THREAD

**Issue by Yandirin** [MathewSachin/Fate-Grand-Automata#87]
As we discussed on the Gamepress thread, it would be good if the script could prioritize a MLB CE if there is both MLB and non-MLB of the same CE onscreen if the MLB option is unchecked.

**Comment by TryBane** [comment]
Not sure how you might change this in this app yet, since I haven't browsed the script files yet (only watched the video so far) but this could be done by providing 2 versions of the CE in the options, one where it looks specifically for MLB and another instance looking for non MLB CE. This is slightly unoptimized since the version looking for non MLB CE will check for both, but it would solve this issue since if it finds the MLB version first, it'll select that one. (This is for the contributors, not for the poster)

**Comment by MathewSachin** [comment]
That's definitely a good idea. We can make it optional for people who don't want to lose performance (I don't think it will be too major 🤔)
